version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
      - ./storage:/app/storage
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
  vue:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: vue
    restart: unless-stopped
    tty: true
    ports:
      - "5173:5173"
    working_dir: /home/node/app
    volumes:
      #      - /home/node/app/node_modules
      - .:/home/node/app
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/app
      - ./storage:/app/storage
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
  #MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker/mysql/db:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
#Volumes:
volumes:
  mysql:
    driver: local
