version: '3'
services:
  #PHP Service
  app:
    build:
      #            args:
      #                user: chaosmos
      #                uid: 1000
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    #        environment:
    #            SERVICE_NAME: ${SERVICE_NAME}
    #            SERVICE_TAG: ${SERVICE_TAG}
    working_dir: /app
    volumes:
      - ./:/app
      - ./storage:/app/storage
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  vue:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: vue
    restart: unless-stopped
    tty: true
    ports:
      - "5173:5173"
#    environment:
#      USER: "node"
#      NPM_CONFIG_PREFIX: "/app/.npm-global"
#      PATH: "${NPM_CONFIG_PREFIX}/bin:${PATH}"
    working_dir: /home/node/app
    volumes:
      - /home/node/app/node_modules
  #            - ./:/app

  #Nginx Service
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    #            - "5173:5173"
    #            - "443:443"
    #
    volumes:
      - ./:/app
      - ./storage:/app/storage
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker/mysql/db:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

#Docker Networks
#networks:
#  app-network:
#    driver: bridge

#Volumes:
volumes:
  mysql:
    driver: local
